// These countries are recognized in the ISO 3166 standard as of 2019 August 24
export const iso3166Countries = [
  { 'name': `Afghanistan`, 'iso3166': 'AF' },
  { 'name': `Åland Islands`, 'iso3166': 'AX' },
  { 'name': `Albania`, 'iso3166': 'AL' },
  { 'name': `Algeria`, 'iso3166': 'DZ' },
  { 'name': `American Samoa`, 'iso3166': 'AS' },
  { 'name': `Andorra`, 'iso3166': 'AD' },
  { 'name': `Angola`, 'iso3166': 'AO' },
  { 'name': `Anguilla`, 'iso3166': 'AI' },
  { 'name': `Antarctica`, 'iso3166': 'AQ' },
  { 'name': `Antigua and Barbuda`, 'iso3166': 'AG' },
  { 'name': `Argentina`, 'iso3166': 'AR' },
  { 'name': `Armenia`, 'iso3166': 'AM' },
  { 'name': `Aruba`, 'iso3166': 'AW' },
  { 'name': `Australia`, 'iso3166': 'AU' },
  { 'name': `Austria`, 'iso3166': 'AT' },
  { 'name': `Azerbaijan`, 'iso3166': 'AZ' },
  { 'name': `Bahamas`, 'iso3166': 'BS' },
  { 'name': `Bahrain`, 'iso3166': 'BH' },
  { 'name': `Bangladesh`, 'iso3166': 'BD' },
  { 'name': `Barbados`, 'iso3166': 'BB' },
  { 'name': `Belarus`, 'iso3166': 'BY' },
  { 'name': `Belgium`, 'iso3166': 'BE' },
  { 'name': `Belize`, 'iso3166': 'BZ' },
  { 'name': `Benin`, 'iso3166': 'BJ' },
  { 'name': `Bermuda`, 'iso3166': 'BM' },
  { 'name': `Bhutan`, 'iso3166': 'BT' },
  { 'name': `Bolivia, Plurinational State of`, 'iso3166': 'BO' },
  { 'name': `Bonaire, Sint Eustatius and Saba`, 'iso3166': 'BQ' },
  { 'name': `Bosnia and Herzegovina`, 'iso3166': 'BA' },
  { 'name': `Botswana`, 'iso3166': 'BW' },
  { 'name': `Bouvet Island`, 'iso3166': 'BV' },
  { 'name': `Brazil`, 'iso3166': 'BR' },
  { 'name': `British Indian Ocean Territory`, 'iso3166': 'IO' },
  { 'name': `Brunei Darussalam`, 'iso3166': 'BN' },
  { 'name': `Bulgaria`, 'iso3166': 'BG' },
  { 'name': `Burkina Faso`, 'iso3166': 'BF' },
  { 'name': `Burundi`, 'iso3166': 'BI' },
  { 'name': `Cambodia`, 'iso3166': 'KH' },
  { 'name': `Cameroon`, 'iso3166': 'CM' },
  { 'name': `Canada`, 'iso3166': 'CA' },
  { 'name': `Cape Verde`, 'iso3166': 'CV' },
  { 'name': `Cayman Islands`, 'iso3166': 'KY' },
  { 'name': `Central African Republic`, 'iso3166': 'CF' },
  { 'name': `Chad`, 'iso3166': 'TD' },
  { 'name': `Chile`, 'iso3166': 'CL' },
  { 'name': `China`, 'iso3166': 'CN' },
  { 'name': `Christmas Island`, 'iso3166': 'CX' },
  { 'name': `Cocos (Keeling) Islands`, 'iso3166': 'CC' },
  { 'name': `Colombia`, 'iso3166': 'CO' },
  { 'name': `Comoros`, 'iso3166': 'KM' },
  { 'name': `Congo`, 'iso3166': 'CG' },
  { 'name': `Congo, the Democratic Republic of the`, 'iso3166': 'CD' },
  { 'name': `Cook Islands`, 'iso3166': 'CK' },
  { 'name': `Costa Rica`, 'iso3166': 'CR' },
  { 'name': `Côte d'Ivoire`, 'iso3166': 'CI' },
  { 'name': `Croatia`, 'iso3166': 'HR' },
  { 'name': `Cuba`, 'iso3166': 'CU' },
  { 'name': `Curaçao`, 'iso3166': 'CW' },
  { 'name': `Cyprus`, 'iso3166': 'CY' },
  { 'name': `Czech Republic`, 'iso3166': 'CZ' },
  { 'name': `Denmark`, 'iso3166': 'DK' },
  { 'name': `Djibouti`, 'iso3166': 'DJ' },
  { 'name': `Dominica`, 'iso3166': 'DM' },
  { 'name': `Dominican Republic`, 'iso3166': 'DO' },
  { 'name': `Ecuador`, 'iso3166': 'EC' },
  { 'name': `Egypt`, 'iso3166': 'EG' },
  { 'name': `El Salvador`, 'iso3166': 'SV' },
  { 'name': `Equatorial Guinea`, 'iso3166': 'GQ' },
  { 'name': `Eritrea`, 'iso3166': 'ER' },
  { 'name': `Estonia`, 'iso3166': 'EE' },
  { 'name': `Ethiopia`, 'iso3166': 'ET' },
  { 'name': `Falkland Islands (Malvinas)`, 'iso3166': 'FK' },
  { 'name': `Faroe Islands`, 'iso3166': 'FO' },
  { 'name': `Fiji`, 'iso3166': 'FJ' },
  { 'name': `Finland`, 'iso3166': 'FI' },
  { 'name': `France`, 'iso3166': 'FR' },
  { 'name': `French Guiana`, 'iso3166': 'GF' },
  { 'name': `French Polynesia`, 'iso3166': 'PF' },
  { 'name': `French Southern Territories`, 'iso3166': 'TF' },
  { 'name': `Gabon`, 'iso3166': 'GA' },
  { 'name': `Gambia`, 'iso3166': 'GM' },
  { 'name': `Georgia`, 'iso3166': 'GE' },
  { 'name': `Germany`, 'iso3166': 'DE' },
  { 'name': `Ghana`, 'iso3166': 'GH' },
  { 'name': `Gibraltar`, 'iso3166': 'GI' },
  { 'name': `Greece`, 'iso3166': 'GR' },
  { 'name': `Greenland`, 'iso3166': 'GL' },
  { 'name': `Grenada`, 'iso3166': 'GD' },
  { 'name': `Guadeloupe`, 'iso3166': 'GP' },
  { 'name': `Guam`, 'iso3166': 'GU' },
  { 'name': `Guatemala`, 'iso3166': 'GT' },
  { 'name': `Guernsey`, 'iso3166': 'GG' },
  { 'name': `Guinea`, 'iso3166': 'GN' },
  { 'name': `Guinea-Bissau`, 'iso3166': 'GW' },
  { 'name': `Guyana`, 'iso3166': 'GY' },
  { 'name': `Haiti`, 'iso3166': 'HT' },
  { 'name': `Heard Island and McDonald Islands`, 'iso3166': 'HM' },
  { 'name': `Holy See (Vatican City State)`, 'iso3166': 'VA' },
  { 'name': `Honduras`, 'iso3166': 'HN' },
  { 'name': `Hong Kong`, 'iso3166': 'HK' },
  { 'name': `Hungary`, 'iso3166': 'HU' },
  { 'name': `Iceland`, 'iso3166': 'IS' },
  { 'name': `India`, 'iso3166': 'IN' },
  { 'name': `Indonesia`, 'iso3166': 'ID' },
  { 'name': `Iran, Islamic Republic of`, 'iso3166': 'IR' },
  { 'name': `Iraq`, 'iso3166': 'IQ' },
  { 'name': `Ireland`, 'iso3166': 'IE' },
  { 'name': `Isle of Man`, 'iso3166': 'IM' },
  { 'name': `Israel`, 'iso3166': 'IL' },
  { 'name': `Italy`, 'iso3166': 'IT' },
  { 'name': `Jamaica`, 'iso3166': 'JM' },
  { 'name': `Japan`, 'iso3166': 'JP' },
  { 'name': `Jersey`, 'iso3166': 'JE' },
  { 'name': `Jordan`, 'iso3166': 'JO' },
  { 'name': `Kazakhstan`, 'iso3166': 'KZ' },
  { 'name': `Kenya`, 'iso3166': 'KE' },
  { 'name': `Kiribati`, 'iso3166': 'KI' },
  { 'name': `Korea, Democratic People's Republic of`, 'iso3166': 'KP' },
  { 'name': `Korea, Republic of`, 'iso3166': 'KR' },
  { 'name': `Kuwait`, 'iso3166': 'KW' },
  { 'name': `Kyrgyzstan`, 'iso3166': 'KG' },
  { 'name': `Lao People's Democratic Republic`, 'iso3166': 'LA' },
  { 'name': `Latvia`, 'iso3166': 'LV' },
  { 'name': `Lebanon`, 'iso3166': 'LB' },
  { 'name': `Lesotho`, 'iso3166': 'LS' },
  { 'name': `Liberia`, 'iso3166': 'LR' },
  { 'name': `Libya`, 'iso3166': 'LY' },
  { 'name': `Liechtenstein`, 'iso3166': 'LI' },
  { 'name': `Lithuania`, 'iso3166': 'LT' },
  { 'name': `Luxembourg`, 'iso3166': 'LU' },
  { 'name': `Macao`, 'iso3166': 'MO' },
  { 'name': `Macedonia, the Former Yugoslav Republic of`, 'iso3166': 'MK' },
  { 'name': `Madagascar`, 'iso3166': 'MG' },
  { 'name': `Malawi`, 'iso3166': 'MW' },
  { 'name': `Malaysia`, 'iso3166': 'MY' },
  { 'name': `Maldives`, 'iso3166': 'MV' },
  { 'name': `Mali`, 'iso3166': 'ML' },
  { 'name': `Malta`, 'iso3166': 'MT' },
  { 'name': `Marshall Islands`, 'iso3166': 'MH' },
  { 'name': `Martinique`, 'iso3166': 'MQ' },
  { 'name': `Mauritania`, 'iso3166': 'MR' },
  { 'name': `Mauritius`, 'iso3166': 'MU' },
  { 'name': `Mayotte`, 'iso3166': 'YT' },
  { 'name': `Mexico`, 'iso3166': 'MX' },
  { 'name': `Micronesia, Federated States of`, 'iso3166': 'FM' },
  { 'name': `Moldova, Republic of`, 'iso3166': 'MD' },
  { 'name': `Monaco`, 'iso3166': 'MC' },
  { 'name': `Mongolia`, 'iso3166': 'MN' },
  { 'name': `Montenegro`, 'iso3166': 'ME' },
  { 'name': `Montserrat`, 'iso3166': 'MS' },
  { 'name': `Morocco`, 'iso3166': 'MA' },
  { 'name': `Mozambique`, 'iso3166': 'MZ' },
  { 'name': `Myanmar`, 'iso3166': 'MM' },
  { 'name': `Namibia`, 'iso3166': 'NA' },
  { 'name': `Nauru`, 'iso3166': 'NR' },
  { 'name': `Nepal`, 'iso3166': 'NP' },
  { 'name': `Netherlands`, 'iso3166': 'NL' },
  { 'name': `New Caledonia`, 'iso3166': 'NC' },
  { 'name': `New Zealand`, 'iso3166': 'NZ' },
  { 'name': `Nicaragua`, 'iso3166': 'NI' },
  { 'name': `Niger`, 'iso3166': 'NE' },
  { 'name': `Nigeria`, 'iso3166': 'NG' },
  { 'name': `Niue`, 'iso3166': 'NU' },
  { 'name': `Norfolk Island`, 'iso3166': 'NF' },
  { 'name': `Northern Mariana Islands`, 'iso3166': 'MP' },
  { 'name': `Norway`, 'iso3166': 'NO' },
  { 'name': `Oman`, 'iso3166': 'OM' },
  { 'name': `Pakistan`, 'iso3166': 'PK' },
  { 'name': `Palau`, 'iso3166': 'PW' },
  { 'name': `Palestine, State of`, 'iso3166': 'PS' },
  { 'name': `Panama`, 'iso3166': 'PA' },
  { 'name': `Papua New Guinea`, 'iso3166': 'PG' },
  { 'name': `Paraguay`, 'iso3166': 'PY' },
  { 'name': `Peru`, 'iso3166': 'PE' },
  { 'name': `Philippines`, 'iso3166': 'PH' },
  { 'name': `Pitcairn`, 'iso3166': 'PN' },
  { 'name': `Poland`, 'iso3166': 'PL' },
  { 'name': `Portugal`, 'iso3166': 'PT' },
  { 'name': `Puerto Rico`, 'iso3166': 'PR' },
  { 'name': `Qatar`, 'iso3166': 'QA' },
  { 'name': `Réunion`, 'iso3166': 'RE' },
  { 'name': `Romania`, 'iso3166': 'RO' },
  { 'name': `Russian Federation`, 'iso3166': 'RU' },
  { 'name': `Rwanda`, 'iso3166': 'RW' },
  { 'name': `Saint Barthélemy`, 'iso3166': 'BL' },
  { 'name': `Saint Helena, Ascension and Tristan da Cunha`, 'iso3166': 'SH' },
  { 'name': `Saint Kitts and Nevis`, 'iso3166': 'KN' },
  { 'name': `Saint Lucia`, 'iso3166': 'LC' },
  { 'name': `Saint Martin (French part)`, 'iso3166': 'MF' },
  { 'name': `Saint Pierre and Miquelon`, 'iso3166': 'PM' },
  { 'name': `Saint Vincent and the Grenadines`, 'iso3166': 'VC' },
  { 'name': `Samoa`, 'iso3166': 'WS' },
  { 'name': `San Marino`, 'iso3166': 'SM' },
  { 'name': `Sao Tome and Principe`, 'iso3166': 'ST' },
  { 'name': `Saudi Arabia`, 'iso3166': 'SA' },
  { 'name': `Senegal`, 'iso3166': 'SN' },
  { 'name': `Serbia`, 'iso3166': 'RS' },
  { 'name': `Seychelles`, 'iso3166': 'SC' },
  { 'name': `Sierra Leone`, 'iso3166': 'SL' },
  { 'name': `Singapore`, 'iso3166': 'SG' },
  { 'name': `Sint Maarten (Dutch part)`, 'iso3166': 'SX' },
  { 'name': `Slovakia`, 'iso3166': 'SK' },
  { 'name': `Slovenia`, 'iso3166': 'SI' },
  { 'name': `Solomon Islands`, 'iso3166': 'SB' },
  { 'name': `Somalia`, 'iso3166': 'SO' },
  { 'name': `South Africa`, 'iso3166': 'ZA' },
  { 'name': `South Georgia and the South Sandwich Islands`, 'iso3166': 'GS' },
  { 'name': `South Sudan`, 'iso3166': 'SS' },
  { 'name': `Spain`, 'iso3166': 'ES' },
  { 'name': `Sri Lanka`, 'iso3166': 'LK' },
  { 'name': `Sudan`, 'iso3166': 'SD' },
  { 'name': `Suriname`, 'iso3166': 'SR' },
  { 'name': `Svalbard and Jan Mayen`, 'iso3166': 'SJ' },
  { 'name': `Swaziland`, 'iso3166': 'SZ' },
  { 'name': `Sweden`, 'iso3166': 'SE' },
  { 'name': `Switzerland`, 'iso3166': 'CH' },
  { 'name': `Syrian Arab Republic`, 'iso3166': 'SY' },
  { 'name': `Taiwan, Province of China`, 'iso3166': 'TW' },
  { 'name': `Tajikistan`, 'iso3166': 'TJ' },
  { 'name': `Tanzania, United Republic of`, 'iso3166': 'TZ' },
  { 'name': `Thailand`, 'iso3166': 'TH' },
  { 'name': `Timor-Leste`, 'iso3166': 'TL' },
  { 'name': `Togo`, 'iso3166': 'TG' },
  { 'name': `Tokelau`, 'iso3166': 'TK' },
  { 'name': `Tonga`, 'iso3166': 'TO' },
  { 'name': `Trinidad and Tobago`, 'iso3166': 'TT' },
  { 'name': `Tunisia`, 'iso3166': 'TN' },
  { 'name': `Turkey`, 'iso3166': 'TR' },
  { 'name': `Turkmenistan`, 'iso3166': 'TM' },
  { 'name': `Turks and Caicos Islands`, 'iso3166': 'TC' },
  { 'name': `Tuvalu`, 'iso3166': 'TV' },
  { 'name': `Uganda`, 'iso3166': 'UG' },
  { 'name': `Ukraine`, 'iso3166': 'UA' },
  { 'name': `United Arab Emirates`, 'iso3166': 'AE' },
  { 'name': `United Kingdom`, 'iso3166': 'GB' },
  { 'name': `United States`, 'iso3166': 'US' },
  { 'name': `United States Minor Outlying Islands`, 'iso3166': 'UM' },
  { 'name': `Uruguay`, 'iso3166': 'UY' },
  { 'name': `Uzbekistan`, 'iso3166': 'UZ' },
  { 'name': `Vanuatu`, 'iso3166': 'VU' },
  { 'name': `Venezuela (Bolivarian Republic of)`, 'iso3166': 'VE' },
  { 'name': `Viet Nam`, 'iso3166': 'VN' },
  { 'name': `Virgin Islands, British`, 'iso3166': 'VG' },
  { 'name': `Virgin Islands, U.S.`, 'iso3166': 'VI' },
  { 'name': `Wallis and Futuna`, 'iso3166': 'WF' },
  { 'name': `Western Sahara`, 'iso3166': 'EH' },
  { 'name': `Yemen`, 'iso3166': 'YE' },
  { 'name': `Zambia`, 'iso3166': 'ZM' },
  { 'name': `Zimbabwe`, 'iso3166': 'ZW' }
];